//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cinema.system
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cinemas
    {
        public Cinemas()
        {
            this.Schedule = new HashSet<Schedule>();
        }
    
        public int ID_cinema { get; set; }
        public string Name_cinema { get; set; }
    
        public virtual ICollection<Schedule> Schedule { get; set; }
    }
}
