//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cinema.system
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CinemaEntities : DbContext
    {
        public CinemaEntities()
            : base("name=CinemaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cinemas> Cinemas { get; set; }
        public DbSet<Country> Country { get; set; }
        public DbSet<Films> Films { get; set; }
        public DbSet<Genre> Genre { get; set; }
        public DbSet<Halls> Halls { get; set; }
        public DbSet<Producers> Producers { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<Schedule> Schedule { get; set; }
        public DbSet<Seats> Seats { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Tickets> Tickets { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
