//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cinema.system
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public Schedule()
        {
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int ID_FilmSession { get; set; }
        public int ID_Film { get; set; }
        public int ID_cinema { get; set; }
        public System.DateTime Date_FilmSession { get; set; }
        public System.TimeSpan Time_FilmSession { get; set; }
    
        public virtual Cinemas Cinemas { get; set; }
        public virtual Films Films { get; set; }
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
