//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cinema.system
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seats
    {
        public Seats()
        {
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int Number_Of_Seat { get; set; }
        public Nullable<int> Number_Hall { get; set; }
        public Nullable<int> Number_Row { get; set; }
        public string Booking_Status { get; set; }
    
        public virtual Halls Halls { get; set; }
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
