//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cinema.system
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int ID_ticket { get; set; }
        public Nullable<int> Number_Of_Seat { get; set; }
        public int Price { get; set; }
        public int ID_FilmSession { get; set; }
    
        public virtual Schedule Schedule { get; set; }
        public virtual Seats Seats { get; set; }
    }
}
