//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cinema.system
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int ID_user { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public int ID_role { get; set; }
        public byte[] UserIcon { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
